version: 2
jobs:
  build:
    docker:
      - image: makarius/isabelle:Isabelle2019
    steps:
      - checkout
      - run: ./test.sh /home/isabelle/Isabelle/bin/isabelle
workflows:
  version: 2
  build:
    jobs:
      - build
